### ISSUE TITLE
Refactor Job Implementation

### ISSUE THREAD

**Issue by fonzdm** [fonzdm/servarr#11]
### Description

At the moment, several pre and post deploy helm jobs are implemented as a series of containers running a "curl equipped" docker image that execute a single, hard to read, GET/POST request.
This introduces several fingerprint overhead and makes it difficult to edit or modify the requests themselves.
Moreover, `evil escapes` are needed to make a proper curl command into the `command` section of a container, for example:

https://github.com/fonzdm/servarr/blob/8a0aa86a082fb902d8c6c5bda303527ed9cafde8/templates/add-indexers-prowlarr.yaml#L36-L40

### Solution you'd like

It would be nice to replace this flow entirely with a proper python/easy-to-read language, as already done for the Jellyseerr post init job:

https://github.com/fonzdm/servarr/blob/8a0aa86a082fb902d8c6c5bda303527ed9cafde8/templates/init-jellyseerr.yaml#L57-L61

The script can be loaded into a configmap and mounted in the hook job, for example:

https://github.com/fonzdm/servarr/blob/8a0aa86a082fb902d8c6c5bda303527ed9cafde8/templates/init-jellyseerr.yaml#L62-L68

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fonzdm** [comment]
@imgios do you feel like taking this? 😃

**Comment by imgios** [comment]
@fonzdm I was checking the project structure that's currently storing the `init-jellyseerr.py` script in `/config/jellyseerr`, but this could be misleading when refactoring the init-downloaders, because it includes all the dependencies init.

What do you think if we place them all in a common directory since we are going to create several Python scripts? I was thinking to something like this:
```shell
.
└── config/
    └── scripts/
        └── *.py
```

**Comment by fonzdm** [comment]
> What do you think if we place them all in a common directory since we are going to create several Python scripts? 

Sounds good! And this will make life easier in case we rely on a single ConfigMap with all the scripts.

**Comment by imgios** [comment]
I was checking the `init-downloaders` job, and I can see that you have a container for each configuration you have to do. I like this approach, this means we may proceed for the init-downloaders script with a single script with x functions, where x is the configurations you have to do, and we can execute them by doing something like that: `init_downloaders.py configure-x`.

What's your POV on that?

**Comment by fonzdm** [comment]
> a single script with x functions, where x is the configurations you have to do, and we can execute them by doing something like that: `init_downloaders.py configure-x`.

It's nice and could allow us to keep the current structure AND have a readable configuration.
Just to point out, we currently have multiple requests in the same jobs towards different services.
Instead of moving everything in one script, what about using different scripts, one per services? (for example, as already done for `jellyseerr `only)

**Comment by imgios** [comment]
> Instead of moving everything in one script, what about using different scripts, one per services? (for example, as already done for `jellyseerr `only)

This is another valid option, would be good to evaluate pros/cons for both solution and see which one may be the best to adopt.

**Comment by fonzdm** [comment]
Ok, let's write down some points.
> Edit: of course is more of an aesthetic thing, as the best method to rule them all is to create a dedicated docker image and write some small library... but it would be another thing to create/maintain/publish.


|Single Script|Multiple Scripts  |
|--|--|
| One implementation (reuse, fix and so on)|Different copies of the same functions (for example, the basic `GET/POST` methods|
| Dependency of different APIs in the same code|Each script refers to a service (and so a set of APIs) |
| One/Few jobs with multiple containers|One job per service, cleaner |
| Difficult to split and maintain  work (one man for the whole script)|Work is splittable and maintainable (one man per service) |
| Easier to test (one invocation = one command)|Harder to test (one flow per service with multiple operations) |
| Easier to add a add a single operation (and ensure idempotency) |Easier to integrate services (for example, readarr is not integrated at the moment, but I wish to do it soon) |
 ||

## Some psudo code for invocation

### Single Script


```yaml
      containers:
        - name: <service>-operation-1
          image: "rapidfort/curl:latest"
          command:
            - "/bin/sh"
            - "-ec"
          args:
            - "python3 -u /mnt/sevarr-configuration.py <service>-operation-1" 
        - name: <service>-operation-2
          image: "rapidfort/curl:latest"
          command:
            - "/bin/sh"
            - "-ec"
          args:
            - "python3 -u /mnt/sevarr-configuration.py <service>-operation-2"
```

Each parameter passed to the script will result in one/few API calls to configure a single feature.

### Multiple Scripts
One job per service, each service will be like:

```yaml
        env:
          - name: ENV_VAR
            value: VALUE
        command:
          - "/bin/sh"
          - "-ec"
        args:
          - "python3 -u /mnt/init-<service>.py 2>&1;"
```
And the `/mnt/init-<service>.py` will execute everything needed for that service (for example, *prowlarr*, with 4 or 5 APIs)


What do you think? I would personally go for the second approach 😄
