### ISSUE TITLE
Helm dependencies condition

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#34]
### Description

Would be good to have a way to select which subchart to deploy.

For instance: if a user wants to deploy Radarr and Sonarr but Flaresolverr.

### Solution you'd like

We can add the condition inside the `Chart.yaml` and have the `values.yaml` with also the enabled field, e.g.,:

```yaml
sonarr:
  enabled: true
  ...
radarr:
  enabled: true
  ...
flaresolverr:
  enabled: false
  ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
