### ISSUE TITLE
storageClass yaml anchor not working 

### ISSUE THREAD

**Issue by emouawad** [fonzdm/servarr#53]
### Description

Installing the chart using remote does not properly replace storageClass yaml anchor.

Are anchors really needed in a helm context, we can use values template instead without anchors

### Steps to reproduce

 i haven't downloaded the chart - maybe that's the reason yaml anchors are not working?

```yaml
helm upgrade -i --namespace servarr --create-namespace --repo https://fonzdm.github.io/servarr --values values.yml servarr servarr --debug
```

### Expected behavior

Chart should replace with the proper values.

### Servarr Helm Chart version

1.0.1

### Relevant log output

```shell
N/A
```

### Chart values

```yaml
global:
  apikey: &apikey "aaa-bbb-ccc-ddd"
  storageClassName: &storageClassName "longhorn"
  ingressClassName: &ingressClassName "nginx"
  certManagerClusterIssuer: &issuer "clusterissuer-self-signed"

metrics:
  enabled: &metricsEnabled false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emouawad** [comment]
Related to [issue](https://github.com/fonzdm/servarr/issues/17)

**Comment by imgios** [comment]
Hi @emouawad, thank you for reporting this! Can I ask you to run the following command to retrieve all the values and share them with us?

```shell
$ helm get values -n <namespace> <release-name> --all
```

@fonzdm let's test this also in our env.

**Comment by emouawad** [comment]
Not an expert on helm charts, but should be able to use helm templates instead of yaml anchors:

I have seen this in many charts - something like this:

```yaml
storageClass: '{{ .Values.global.storageClassName }}'
```

**Comment by imgios** [comment]
I see your point, and this technique is really helpful when you are modelling resources within the chart, e.g.,:
https://github.com/fonzdm/servarr/blob/80b51c00d253efb14e5ea540b7e85fa5ce2d8f2e/servarr/templates/pvc.yaml#L12

In this case, the aim is to reduce the amount of duplicate parameters required for the subcharts installation (`*rr` apps), which are responsible to (define and) deploy each app, that's why we are using anchors.

**Comment by imgios** [comment]
Hi, I'm closing this since we didn't get any further answers from @emouawad and the issue is not reproducible.

**Comment by imgios** [comment]
I have been testing this with the [following `values.yaml`](https://github.com/fonzdm/servarr/blob/servarr-1.0.1/servarr/values.yaml) (providing the inputs required: API Key, credentials, etc.) and it was working fine. The issue is happening when the values passed are not including the parameter that uses the anchors references (just like your values), e.g.:

https://github.com/fonzdm/servarr/blob/80b51c00d253efb14e5ea540b7e85fa5ce2d8f2e/servarr/values.yaml#L481

https://github.com/fonzdm/servarr/blob/80b51c00d253efb14e5ea540b7e85fa5ce2d8f2e/servarr/values.yaml#L526

A workaround is to provide a minimal `values.yaml` that includes these lines with the anchors references.

<details><summary>Minimal <code>values.yaml</code></summary>

```yaml
global:
  apikey: &apikey
  storageClassName: &storageClassName "network-block"
  ingressClassName: &ingressClassName "nginx"
  certManagerClusterIssuer: &issuer

metrics:
  enabled: &metricsEnabled false

dash:
  username:
  password:
  mail:
  countryCode: "US"
  preferredLanguage: "en"

torrent:
  username:
  password:

volumes:
  storageClass: *storageClassName
  downloads:
    name: &downloads-volume downloads-volume
    size: 100Gi
  media:
    name: &media-volume media-volume
    size: 250Gi
  torrentConfig:
    name: &torrentConfig torrent-config
    size: 250Mi

sonarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              SONARR__API_KEY: *apikey
  ingress:
    sonarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: sonarr.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr.local
          secretName: sonarr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume
    downloads:
      existingClaim: *downloads-volume

radarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              RADARR__API_KEY: *apikey
  ingress:
    radarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: radarr.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - radarr.local
          secretName: radarr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume
    downloads:
      existingClaim: *downloads-volume

jellyfin:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    jellyfin-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyfin.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyfin.local
          secretName: jellyfin-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume

jellyseerr:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    jellyseerr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyseerr.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyseerr.local
          secretName: jellyseerr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume

qbittorrent:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    qbittorrent-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: torrent.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - torrent.local
          secretName: torrent-tls
  persistence:
    config:
      existingClaim: *torrentConfig
    downloads:
      existingClaim: *downloads-volume

prowlarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              PROWLARR__API_KEY: *apikey
  ingress:
    prowlarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: prowlarr.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - prowlarr.local
          secretName: prowlarr-tls
  persistence:
    config:
      storageClass: *storageClassName

flaresolverr:
  metrics:
    main:
      enabled: *metricsEnabled
  persistence:
    config:
      storageClass: *storageClassName
```

</details>

**Comment by imgios** [comment]
I have been testing this again, and seems like there's an issue with the anchors. Moreover, even if we pass the following values for the anchors:

```yaml
global:
  apikey: &apikey "gGqp2b8maEzd2MrrIuDIwdWArgtEdWHf59fJFzoj8r4qcAZe4iHiqmDO7RBHaYYh"
  storageClassName: "longhorn"
  ingressClassName: "traefik"
  certManagerClusterIssuer: &issuer
```

In some places - mainly in the subcharts globals - they are set still with the default Chart value:

```yaml
<service-name>:
  global:
    apikey: null
    certManagerClusterIssuer: null
    ingressClassName: nginx
    storageClassName: network-block
```

**Comment by imgios** [comment]
Hi @emouawad,

Seems like I was right when I said this:

> The issue is happening when the values passed are not including the parameters with the anchors references.

I have been using the following values and they're setting the right storage class:

<details>
<summary>Minimal Values</summary>

```yaml
global:
  apikey: &apikey "909be0c2-337a-4a0b-b7f0-7e0847338296"
  storageClassName: &storageClassName "nas"
  ingressClassName: &ingressClassName "tailscale"
  certManagerClusterIssuer: &issuer

metrics:
  enabled: &metricsEnabled false

dash:
  username: imgios
  password: imgios@github
  mail: imgios@servarr.local
  countryCode: "US"
  preferredLanguage: "en"

torrent:
  username: imgios
  password: imgios@github

volumes:
  storageClass: *storageClassName
  downloads:
    name: &downloads-volume downloads-volume
    size: 100Gi
  media:
    name: &media-volume media-volume
    size: 250Gi
  torrentConfig:
    name: &torrentConfig torrent-config
    size: 250Mi

sonarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              SONARR__API_KEY: *apikey
  ingress:
    sonarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: sonarr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr
          secretName: sonarr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume
    downloads:
      existingClaim: *downloads-volume

radarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              RADARR__API_KEY: *apikey
  ingress:
    radarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: radarr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - radarr
          secretName: radarr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume
    downloads:
      existingClaim: *downloads-volume

jellyfin:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    jellyfin-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyfin
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyfin
          secretName: jellyfin-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume

jellyseerr:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    jellyseerr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyseerr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyseerr
          secretName: jellyseerr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume

qbittorrent:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    qbittorrent-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: torrent
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - torrent
          secretName: torrent-tls
  persistence:
    config:
      existingClaim: *torrentConfig
    downloads:
      existingClaim: *downloads-volume

prowlarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              PROWLARR__API_KEY: *apikey
  ingress:
    prowlarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: prowlarr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - prowlarr
          secretName: prowlarr-tls
  persistence:
    config:
      storageClass: *storageClassName

flaresolverr:
  metrics:
    main:
      enabled: *metricsEnabled
  persistence:
    config:
      storageClass: *storageClassName
```

</details>

Can you test them and let us know?
