### ISSUE TITLE
Installation fails on ARM architecture

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#64]
### Description

The installation on `arm-based` devices is failing with the `pre-init-job` not being run at all. From a first analysis, the `dinutac/jinja2docker:2.1.8` container image could be the root cause, since it's built only for `linux/amd64`. The same assumption is valid also for `rapidfort/curl`.

### Steps to reproduce

Deploy Servarr on an arm device (e.g., Raspberry Pis, SBC, ..)

### Expected behavior

At least the pre-init-job should run successfully.

### Servarr Helm Chart version

1.0.1

### Relevant log output

```shell
exec /usr/bin/sh: exec format error
```

### Chart values

```yaml
global:
  apikey: &apikey "gGqp2b8maEzd2MrrIuDIwdWArgtEdWHf59fJFzoj8r4qcAZe4iHiqmDO7RBHaYYh"
  storageClassName: &storageClassName "longhorn"
  ingressClassName: &ingressClassName "traefik"
  certManagerClusterIssuer: &issuer

dash:
  username: imgios
  password: supers3cret
  mail: imgios@homelab.local
  countryCode: "IT"
  preferredLanguage: "en"

torrent:
  username: imgios
  password: supers3cret

volumes:
  storageClass: *storageClassName
  downloads:
    name: &downloads-volume downloads-volume
    size: 10Gi
  media:
    name: &media-volume media-volume
    size: 10Gi
  torrentConfig:
    name: &torrentConfig torrent-config
    size: 250Mi
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
