### ISSUE TITLE
Init jobs are failing if the release name isn't `servarr`

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#71]
### Description

The deployment fails if the release name isn't `servarr`, cause the init jobs will try to reach the services using the following pattern:

```
http://{{ .Release.Namespace }}-<service-name>.{{ .Release.Namespace }}.svc.cluster.local:<port>
```

But the services are created using the following pattern: `{{ .Release.Name }}-<service-name>`

### Steps to reproduce

```shell
helm install servarr-min fonzdm/servarr \
--namespace servarr \
--create-namespace \
--values values.yaml
```

### Expected behavior

The init job should be using the release name to correctly resolve the service.

### Servarr Helm Chart version

1.0.1

### Relevant log output

```shell
$ kubectl logs -n servarr radarr-init-7fw8d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: servarr-radarr.servarr.svc.cluster.local
waiting for servarr-radarr
$ kubectl get svc -n servarr | grep radarr
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
servarr-min-radarr                   ClusterIP   10.102.211.219   <none>        7878/TCP            9m52s
```

### Chart values

```yaml
global:
  apikey: &apikey "909be0c2-337a-4a0b-b7f0-7e0847338296" # this is a sample key
  storageClassName: &storageClassName "nas"
  ingressClassName: &ingressClassName "tailscale"
  certManagerClusterIssuer: &issuer

metrics:
  enabled: &metricsEnabled false

dash:
  username: imgios
  password: imgios@github
  mail: imgios@servarr.local
  countryCode: "US"
  preferredLanguage: "en"

torrent:
  username: imgios
  password: imgios@github

volumes:
  storageClass: *storageClassName
  downloads:
    name: &downloads-volume downloads-volume
    size: 5Gi
  media:
    name: &media-volume media-volume
    size: 5Gi
  torrentConfig:
    name: &torrentConfig torrent-config
    size: 250Mi

sonarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              SONARR__API_KEY: *apikey
  ingress:
    sonarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: sonarr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - sonarr
          secretName: sonarr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume
    downloads:
      existingClaim: *downloads-volume

radarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              RADARR__API_KEY: *apikey
  ingress:
    radarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: radarr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - radarr
          secretName: radarr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume
    downloads:
      existingClaim: *downloads-volume

jellyfin:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    jellyfin-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyfin
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyfin
          secretName: jellyfin-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume

jellyseerr:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    jellyseerr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: jellyseerr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyseerr
          secretName: jellyseerr-tls
  persistence:
    config:
      storageClass: *storageClassName
    media:
      existingClaim: *media-volume

qbittorrent:
  metrics:
    main:
      enabled: *metricsEnabled
  ingress:
    qbittorrent-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: torrent
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - torrent
          secretName: torrent-tls
  persistence:
    config:
      existingClaim: *torrentConfig
    downloads:
      existingClaim: *downloads-volume

prowlarr:
  metrics:
    main:
      enabled: *metricsEnabled
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              PROWLARR__API_KEY: *apikey
  ingress:
    prowlarr-ing:
      annotations:
        cert-manager.io/cluster-issuer: *issuer
      ingressClassName: *ingressClassName
      hosts:
        - host: prowlarr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - prowlarr
          secretName: prowlarr-tls
  persistence:
    config:
      storageClass: *storageClassName

flaresolverr:
  metrics:
    main:
      enabled: *metricsEnabled
  persistence:
    config:
      storageClass: *storageClassName
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
