### ISSUE TITLE
vpn setup for qbittorrent and prowlarr

### ISSUE THREAD

**Issue by Dialgatrainer02** [fonzdm/servarr#73]
### Description

my isp blocks certain indexers like 1337x, adding vpn configuration options would bypass my isp allowing qbit and prowlarr to access those sites

### Solution you'd like

the true charts qbittorrent image can use gluten vpn as an addon https://truecharts.org/guides/addons/vpn-setup/. then you should be able to add a section in the values file for the vpn. i belive the same addon should work for prowlarr, if not something like privoxy to allow prowlarr to use the vpn.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kernelb00t** [comment]
Hello! Did you tried changing your DNS?? Because if my ISP was blocking IPs I would change the ISP, not my homelab 😅 

Nevertheless, having VPN configuration would be awesome. For my part, I'm French and the government scans known trackers, hunting for IPs seeding DMCA'd torrents and sends a cease-and-desist letter to the box owner 🥇 so yeah, a VPN at least for seeding is required.

In my mind, it would something like :
```yaml
gluetun:
  # <define your connection details here, secrets etc...>

prowlarr: 
  vpn:
    enabled: false

qBittorrent:
  vpn:
    enabled: false

# Other services...
```
This would allow everyone to have a clean config and adapt to all sorts of situations.
